include: package:blendthink_lints/recommended.yaml

linter:
  rules:
    exclude:
      # 研修なのでエラーの扱い方に重点を置かない
      - only_throw_errors

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: error
  plugins:
    - custom_lint
