name: flutter_training
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.5

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.1.1
  simple_logger: ^1.9.0+2
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/weather_icons/
